name: Build MixinBlocker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v4

      - name: Build mod
        run: ./gradlew jar
      
      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: MixinBlocker Jar
          path: '**/build/libs/*.jar'
